### ISSUE TITLE
python3 cannot write file

### ISSUE THREAD

**Issue by sinkaszab** [tbodt/ish#272]
Cache files are created but then cannot be written. I gave “nodeids” group and other write permission, but didn’t help.

```bash
➜  mygrate git:(master) ✗ pytest                                                                       
========================================= test session starts =========================================
platform linux -- Python 3.6.6, pytest-4.1.0, py-1.7.0, pluggy-0.8.1                                   
rootdir: /root/mygrate, inifile:                                                                       
collecting ...                                                                                         
========================================== warnings summary ===========================================
/usr/lib/python3.6/site-packages/_pytest/cacheprovider.py:131                                          
  /usr/lib/python3.6/site-packages/_pytest/cacheprovider.py:131: PytestWarning: cache could not write p
ath /root/mygrate/.pytest_cache/v/cache/stepwise                                                       
    self.warn("cache could not write path {path}", path=path)                                          
  /usr/lib/python3.6/site-packages/_pytest/cacheprovider.py:131: PytestWarning: cache could not write p
ath /root/mygrate/.pytest_cache/v/cache/nodeids                                                        
    self.warn("cache could not write path {path}", path=path)                                          
                                                                                                       
-- Docs: https://docs.pytest.org/en/latest/warnings.html                                               
===================================== 2 warnings in 0.89 seconds ======================================
Traceback (most recent call last):                                                                     
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 203, in wrap_session                   
    session.exitstatus = doit(config, session) or 0                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 242, in _main                          
    config.hook.pytest_collection(session=session)                                                     
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__                       
    return self._hookexec(self, self.get_hookimpls(), kwargs)                                          
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec                     
    return self._inner_hookexec(hook, methods, kwargs)                                                 
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>                      
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                             
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall                   
    return outcome.get_result()                                                                        
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result                    
    raise ex[1].with_traceback(ex[2])                                                                  
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall                   
    res = hook_impl.function(*args)                                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 252, in pytest_collection              
    return session.perform_collect()                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 465, in perform_collect                
    items = self._perform_collect(args, genitems)                                                      
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 504, in _perform_collect               
    self.items.extend(self.genitems(node))                                                             
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 731, in genitems                       
    rep = collect_one_node(node)                                                                       
  File "/usr/lib/python3.6/site-packages/_pytest/runner.py", line 407, in collect_one_node             
    rep = ihook.pytest_make_collect_report(collector=collector)                                        
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__                       
    return self._hookexec(self, self.get_hookimpls(), kwargs)                                          
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec                     
    return self._inner_hookexec(hook, methods, kwargs)                                                 
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>                      
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                             
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall                   
    gen.send(outcome)                                                                                  
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 195, in pytest_make_collect_report  
    out, err = self.read_global_capture()                                                              
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 131, in read_global_capture         
    return self._global_capturing.readouterr()                                                         
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 494, in readouterr                  
    self.out.snap() if self.out is not None else "",                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 588, in snap                        
    res = FDCaptureBinary.snap(self)                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 552, in snap                        
    self.tmpfile.truncate()                                                                            
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by tbodt** [comment]
That output unfortunately doesn't include the real error. Could you add `raise` right before line 131 in /usr/lib/python3.6/site-packages/_pytest/cacheprovider.py, and send me the different error message?

**Comment by sinkaszab** [comment]
I will provide further debug information.

**Comment by tbodt** [comment]
@sinkaszab have you obtained the extra debug information?

**Comment by tbodt** [comment]
@sinkaszab friendly ping

**Comment by sinkaszab** [comment]
With the latest iSH version I have the first error message has disappeared regarding pycache.

This traceback is useless for me, I don’t want to end up in an infinite debugging, sry.

```
========================================= test session starts =========================================
platform linux -- Python 3.6.6, pytest-4.3.1, py-1.7.0, pluggy-0.8.1                                   
rootdir: /root/repositories/mygrate/mygrate/test, inifile:                                             
collecting 0 items                                                                                     
==================================== no tests ran in 2.04 seconds =====================================
Traceback (most recent call last):                                                                     
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 209, in wrap_session                   
    session.exitstatus = doit(config, session) or 0                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 248, in _main                          
    config.hook.pytest_collection(session=session)                                                     
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__                       
    return self._hookexec(self, self.get_hookimpls(), kwargs)                                          
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec                     
    return self._inner_hookexec(hook, methods, kwargs)                                                 
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>                      
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                             
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall                   
    return outcome.get_result()                                                                        
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result                    
    raise ex[1].with_traceback(ex[2])                                                                  
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall                   
    res = hook_impl.function(*args)                                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 258, in pytest_collection              
    return session.perform_collect()                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 485, in perform_collect                
    items = self._perform_collect(args, genitems)                                                      
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 524, in _perform_collect               
    self.items.extend(self.genitems(node))                                                             
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 759, in genitems                       
    rep = collect_one_node(node)                                                                       
  File "/usr/lib/python3.6/site-packages/_pytest/runner.py", line 407, in collect_one_node             
    rep = ihook.pytest_make_collect_report(collector=collector)                                        
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__                       
    return self._hookexec(self, self.get_hookimpls(), kwargs)                                          
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec                     
    return self._inner_hookexec(hook, methods, kwargs)                                                 
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>                      
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                             
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall                   
    gen.send(outcome)                                                                                  
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 196, in pytest_make_collect_report  
    out, err = self.read_global_capture()                                                              
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 132, in read_global_capture         
    return self._global_capturing.readouterr()                                                         
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 499, in readouterr                  
    self.out.snap() if self.out is not None else "",                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 593, in snap                        
    res = FDCaptureBinary.snap(self)                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 557, in snap                        
    self.tmpfile.truncate()                                                                            
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:                                    
                                                                                                       
Traceback (most recent call last):                                                                     
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 225, in wrap_session                   
    config.notify_exception(excinfo, config.option)                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 684, in notify_exception    
    res = self.hook.pytest_internalerror(excrepr=excrepr, excinfo=excinfo)                             
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__                       
    return self._hookexec(self, self.get_hookimpls(), kwargs)                                          
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec                     
    return self._inner_hookexec(hook, methods, kwargs)                                                 
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>                      
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                             
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall                   
    return outcome.get_result()                                                                        
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result                    
    raise ex[1].with_traceback(ex[2])                                                                  
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall                   
    res = hook_impl.function(*args)                                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 232, in pytest_internalerror        
    self.stop_global_capturing()                                                                       
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 116, in stop_global_capturing       
    self._global_capturing.pop_outerr_to_orig()                                                        
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 459, in pop_outerr_to_orig          
    out, err = self.readouterr()                                                                       
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 499, in readouterr                  
    self.out.snap() if self.out is not None else "",                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 593, in snap                        
    res = FDCaptureBinary.snap(self)                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 557, in snap                        
    self.tmpfile.truncate()                                                                            
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:                                    
                                                                                                       
Traceback (most recent call last):                                                                     
  File "/usr/bin/pytest", line 10, in <module>                                                         
    sys.exit(main())                                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 79, in main                 
    return config.hook.pytest_cmdline_main(config=config)                                              
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__                       
    return self._hookexec(self, self.get_hookimpls(), kwargs)                                          
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec                     
    return self._inner_hookexec(hook, methods, kwargs)                                                 
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>                      
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                             
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall                   
    return outcome.get_result()                                                                        
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result                    
    raise ex[1].with_traceback(ex[2])                                                                  
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall                   
    res = hook_impl.function(*args)                                                                    
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 242, in pytest_cmdline_main            
    return wrap_session(config, _main)                                                                 
  File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 237, in wrap_session                   
    config._ensure_unconfigure()                                                                       
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 647, in _ensure_unconfigure 
    fin()                                                                                              
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 116, in stop_global_capturing       
    self._global_capturing.pop_outerr_to_orig()                                                        
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 459, in pop_outerr_to_orig          
    out, err = self.readouterr()                                                                       
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 499, in readouterr                  
    self.out.snap() if self.out is not None else "",                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 593, in snap                        
    res = FDCaptureBinary.snap(self)                                                                   
  File "/usr/lib/python3.6/site-packages/_pytest/capture.py", line 557, in snap                        
    self.tmpfile.truncate()                                                                            
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by tbodt** [comment]
Seems to be fixed now.

**Comment by sinkaszab** [comment]
You mean the latest version of iSH works well with pytest? Because although it doesn't show cacheprovider error, the tests don't run in my version.

**Comment by tbodt** [comment]
I just ran a test on the master branch and it worked. I'll let you know when I release an update tomorrow so you can try it yourself.
