### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by Zxilly** [tbodt/ish#328]
iPad:~# pip3 -V                                                                                                                 
^CFailed to import the site module                                                                                              
Traceback (most recent call last):                                                                                              
  File "/usr/lib/python3.6/site.py", line 73, in <module>                                                                       
    import os                                                                                                                   
  File "/usr/lib/python3.6/os.py", line 57, in <module>                                                                         
    import posixpath as path                                                                                                    
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                             
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                                                    
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                             
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module                                                       
  File "<frozen importlib._bootstrap_external>", line 779, in get_code                                                          
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode                                                 
KeyboardInterrupt

**Comment by tbodt** [comment]
You didn't wait long enough

**Comment by Zxilly** [comment]
In fact,I wait almost 5 min and press ctrl+v

**Comment by tbodt** [comment]
Hmm that is a long time. But it really seems like you interrupted it while it was making progress on initializing. Do you get a slightly different error if you try again?

**Comment by youtux** [comment]
Same problem here with an iPhone X, `pip` takes a very long time, even to just display the version:

```
Axiom:~# which pip                                
/usr/bin/pip                                      
Axiom:~# time pip --version                       
pip 19.2.1 from /usr/lib/python3.6/site-packages/p
ip (python 3.6)                                   
real    0m 23.68s                                 
user    0m 23.35s                                 
sys     0m 0.00s   
```
