### ISSUE TITLE
SemLock error?

### ISSUE THREAD

**Issue by watosar** [tbodt/ish#522]
When I tried to build Python3.8 and run `make altinstall` command, this error happened.

dmesg returned `8 stub system call 375`

Following is the full traceback of my error.
```
/usr/bin/install -c -m 644 `cat pybuilddir.txt`/_sysconfigdata__linux_i386-linux-gnu.py \
        /usr/local/lib/python3.8; \
/usr/bin/install -c -m 644 ./LICENSE /usr/local/lib/python3.8/LICENSE.txt
if test -d /usr/local/lib/python3.8/distutils/tests; then \
        /usr/bin/install -c -m 644 ./Modules/xxmodule.c \
                /usr/local/lib/python3.8/distutils/tests ; \
fi
PYTHONPATH=/usr/local/lib/python3.8   \
        ./python -E -Wi /usr/local/lib/python3.8/compileall.py \
        -j0 -d /usr/local/lib/python3.8 -f \
        -x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
        /usr/local/lib/python3.8
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/root/Python-3.8.0/build/lib.linux-i686-3.8/_multiprocessing.cpython-38-i386-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/usr/local/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/usr/local/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
make: [Makefile:1415: libinstall] Error 1 (ignored)
PYTHONPATH=/usr/local/lib/python3.8  \
        ./python -E -Wi -O /usr/local/lib/python3.8/compileall.py \
        -j0 -d /usr/local/lib/python3.8 -f \
        -x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
        /usr/local/lib/python3.8
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/root/Python-3.8.0/build/lib.linux-i686-3.8/_multiprocessing.cpython-38-i386-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/usr/local/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/usr/local/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
make: [Makefile:1416: libinstall] Error 1 (ignored)
PYTHONPATH=/usr/local/lib/python3.8  \
        ./python -E -Wi -OO /usr/local/lib/python3.8/compileall.py \
        -j0 -d /usr/local/lib/python3.8 -f \
        -x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
        /usr/local/lib/python3.8
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/root/Python-3.8.0/build/lib.linux-i686-3.8/_multiprocessing.cpython-38-i386-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/usr/local/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/usr/local/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
make: [Makefile:1417: libinstall] Error 1 (ignored)
PYTHONPATH=/usr/local/lib/python3.8  \
        ./python -E -Wi /usr/local/lib/python3.8/compileall.py \
        -j0 -d /usr/local/lib/python3.8/site-packages -f \
        -x badsyntax /usr/local/lib/python3.8/site-packages
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/root/Python-3.8.0/build/lib.linux-i686-3.8/_multiprocessing.cpython-38-i386-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/usr/local/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/usr/local/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
make: [Makefile:1418: libinstall] Error 1 (ignored)
PYTHONPATH=/usr/local/lib/python3.8  \
        ./python -E -Wi -O /usr/local/lib/python3.8/compileall.py \
        -j0 -d /usr/local/lib/python3.8/site-packages -f \
        -x badsyntax /usr/local/lib/python3.8/site-packages
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/root/Python-3.8.0/build/lib.linux-i686-3.8/_multiprocessing.cpython-38-i386-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/usr/local/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/usr/local/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
make: [Makefile:1419: libinstall] Error 1 (ignored)
PYTHONPATH=/usr/local/lib/python3.8  \
        ./python -E -Wi -OO /usr/local/lib/python3.8/compileall.py \
        -j0 -d /usr/local/lib/python3.8/site-packages -f \
        -x badsyntax /usr/local/lib/python3.8/site-packages
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/root/Python-3.8.0/build/lib.linux-i686-3.8/_multiprocessing.cpython-38-i386-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/compileall.py", line 327, in <module>
    exit_status = int(not main())
  File "/usr/local/lib/python3.8/compileall.py", line 309, in main
    if not compile_dir(dest, maxlevels, args.ddir,
  File "/usr/local/lib/python3.8/compileall.py", line 85, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
make: [Makefile:1420: libinstall] Error 1 (ignored)
```

**Comment by tbodt** [comment]
How did you build it? Just default `./configure` and `make`?

**Comment by watosar** [comment]
Yes

**Comment by watosar** [comment]
`./configure CXX=g++ --enable-optimizations` and `make`  
  
I'm sorry if I made you some misunderstanding. 
My build succeeded and Python3.8 is correctly working.
Just I meant to tell you this error was happened.

**Comment by tbodt** [comment]
Ah, so the install failed, not the build. Gotcha.

**Comment by tbodt** [comment]
Closing as "works on my machine"
