### ISSUE TITLE
[BUG] Getting error with media files when using `python http.server`

### ISSUE THREAD

**Issue by wenmin-wu** [tbodt/ish#556]
When I use python http.server, it works fine with text files. However, it doesn’t work with media files like `mp4`. The error logs are as following:
```
wenminteki-iPad:~/ai-for-trading# python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [12/Nov/2019 12:38:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Nov/2019 12:38:46] "GET /Udacity%20-%20Artificial%20Intelligence%20AI%20for%20Trading%20v1.0.0/Part%2001-Module%2001-Lesson%2001_Welcome%20to%20the%20Nanodegree%20Program/01.%20M1L1%2001%20Welcome%20V1-W2R32yXgwcg.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [12/Nov/2019 12:38:46] "GET /Udacity%20-%20Artificial%20Intelligence%20AI%20for%20Trading%20v1.0.0/Part%2001-Module%2001-Lesson%2001_Welcome%20to%20the%20Nanodegree%20Program/01.%20M1L1%2001%20Welcome%20V1-W2R32yXgwcg.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50073)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50074)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/lib/python3.7/http/server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 844, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/lib/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
  File "/usr/lib/python3.7/http/server.py", line 653, in do_GET
    self.copyfile(f, self.wfile)
BrokenPipeError: [Errno 32] Broken pipe
  File "/usr/lib/python3.7/http/server.py", line 844, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
----------------------------------------
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by tbodt** [comment]
This doesn't actually seem like an iSH bug, the same thing happens when running `python3 -m http.server` outside of iSH on my mac and trying to open a video in Safari.
