### ISSUE TITLE
About pip3

### ISSUE THREAD

**Issue by 435390736** [tbodt/ish#594]
After install python3,I want to install numpy and some other packages.But whatever I input about pip3, it always says
“ Traceback (most recent call last):
  File "/usr/bin/pip3", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 20, in <module>
    from pip._internal.utils.hashes import STRONG_HASHES
  File "/usr/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 10, in <module>
    from pip._internal.utils.misc import read_chunks
  File "/usr/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 21, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found”

I searched it on the internet but got no answer.
How can I solve it?
Thank you

**Comment by tbodt** [comment]
It's working for me. How did you install pip3?

**Comment by Rexogamer** [comment]
for me, APK can’t find PIP

**Comment by tbodt** [comment]
It's py2-pip

**Comment by Rexogamer** [comment]
ah, what about python 3

**Comment by tbodt** [comment]
That's just part of python3

**Comment by tbodt** [comment]
Closing for lack of reproduction case, will reopen if one turns up
