### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED running meson build

### ISSUE THREAD

**Issue by devzero0** [tbodt/ish#91]
macOS 10.14, Python 3.6.7

```
$ meson build
The Meson build system
Version: 0.48.2
Source dir: /Users/user/Downloads/ish
Build dir: /Users/user/Downloads/ish/build
Build type: native build
Project name: ish
Project version: undefined
Native C compiler: cc (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.11.45.5)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES 
Library rt found: NO
Downloading gdbm from https://mirrors.kernel.org/gnu/gdbm/gdbm-1.18.tar.gz
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 136, in generate
    self._generate(env)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 165, in _generate
    intr.run()
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 3836, in run
    super().run()
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 411, in evaluate_statement
    return self.assignment(cur)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 946, in assignment
    value = self.evaluate_statement(node.value)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 413, in evaluate_statement
    return self.method_call(cur)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 715, in method_call
    obj = self.evaluate_statement(invokable)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 705, in function_call
    return func(node, posargs, kwargs)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 133, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2278, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2317, in do_subproject
    resolved = r.resolve(dirname)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 146, in resolve
    self.download(p, packagename)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 328, in download
    dhash, tmpfile = self.get_data(srcurl)
  File "/Users/user/.virtualenvs/ish/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 278, in get_data
    resp = urllib.request.urlopen(url, timeout=req_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
```

**Comment by devzero0** [comment]
My bad, this issue is clearly stated in the [Python 3.6 release notes](https://www.python.org/downloads/release/python-360/). The solution was to run `/Applications/Python\ 3.6/Install\ Certificates.command`
